### ISSUE TITLE
Island formation

### ISSUE THREAD

**Issue by Mineshaft87** [Quidvio/Floating-Islands-1.19#2]
Hi,
I was wondering what settings i would change to make the islands less varied Y axis wise and more uniform at their floating height? Thanks! Love the datapack.

EDIT: Oh and what settings could i adjust to widen the void gaps between the islands, that would be awesome to know.

**Comment by klinbee** [comment]
[density_function.zip](https://github.com/Quidvio/Floating-Islands-1.19/files/9571341/density_function.zip)
In worldgen/noise_settings/overworld.json, look for "final_density" there should be 3 y-clamped gradients, ignore the first one. These determine cut-offs of the noise vertically (1 = block, 0 = no block; could be something more like 0> or 0< I don't entirely remember).  If what you meant by "less varied y-axis wise" you can make the ranges of the y-clamped gradients (one is at the bottom of the world, the other is a transition at the top) smaller and so you can just have islands at like y=30. 

If you mean less varied y-axis wise based on the noise (aka less overhangs, more flat walls on the islands), in worldgen/density_function/end/base_3d_noise, the y_scale determines how stretched or squished the y-axis noise is. Similarly, the xz-scale can create more voids if increased or decreased (I think). 

Another way to create more voids would be to lower the value in the y_clamped_gradient mentioned in the first paragraph. The lower one to be specific, so from like 0.6 to 0.5. Going too low however will just cause islands to not spawn except for the aquifers because they literally don't care.

Glad you're enjoying it. :)

EDIT: There is no worldgen/density_function folder, let me attach the default to this message so you can fiddle with it. Just copy density_function into your worldgen folder in the datapack.
