### ISSUE TITLE
Works in single player but not on server

### ISSUE THREAD

**Issue by AlexisBG06** [Quidvio/Floating-Islands-1.19#3]
Hi, thanks a lot for this datapack, I'm very happy to be able to play with the floating generation again :)
It works flawlessly in single player, although when I put the map/world on my server, the floating island generation is still there, I even got the zone that got rendered in single player, but beyond that zone, it will only generate "frozen river/river" biome, higher, but which actually more feel like plains/raw cold biome. (on the server)
It doesn't do that in single player though. Maybe I'm not putting the world correctly to the server? All I did was creating the map (with the datapack) in single player, copy pasting it on my server...
Any clue?
Btw it's a paper server :)

**Comment by klinbee** [comment]
I think it's likely because when you copy the world over alone, it's not going to be storing the datapack correctly on a server and only storing the base-world gen. There should be a datapack folder on a server, I would try putting the datapack in there and seeing if that fixes it. 

If not I'm honestly unsure how I would test it to fix it...

**Comment by AlexisBG06** [comment]
Well there isn't any data packs folder in the server directory, only in the world folders.
I checked the world folder, and your datapack is still there. I noticed that another datapack got added to this world "bukkit"...

**Comment by klinbee** [comment]
Yeahhh after I sent that, I was afraid that would be the case. Testing to fix also seems tedious because I would have to set-up a server, which I've done like 2 times total and do not wish to do that right now lol. 

However with some minor research I've done, can you try doing /datapack list. If it is not on there, do /reload from console (or if you have perms in game).

**Comment by AlexisBG06** [comment]
So after checking, the datapack does appear in /datapack list.
Although I noticed a setting in server.properties: generator-settings={}
Maybe there should be sth in there? https://minecraft.fandom.com/wiki/Java_Edition_level_format#generatorOptions_tag_format
Also if I can help in testing please let me know^^

**Comment by klinbee** [comment]
Hmm maybe but I am unsure.

Yes, your help would be appreciated. I will let you know whenever I am not busy and can try to see what is going on.

Contact me on discord at Quidvio#4760, and I will dm you back and tell you whenever I am available (prob in an hour or two).

Also, you probably did this, but make sure that it is enabled, not just in the list. When you do /datapack list it does pop up all of them, but (and I didn't know about this) /datapack list enabled  will show you the datapacks that are currently enabled.
