### ISSUE TITLE
Bulky islands spread out

### ISSUE THREAD

**Issue by jamesol1** [Quidvio/Floating-Islands-1.19#4]
Love the datapack, by the far the best floating island gen i've seen!
I was wondering if you could release a download for the first version of a more spaced out/larger floating islands world as shown in this video: https://www.youtube.com/watch?v=8w-LkG9Gi-Y&ab_channel=Quidvio
(which was the first one shown in it).
This generation has a similar look to previous floating island gens that have been quite popular in the past! Would make for some awesome gameplay!

Thanks!

**Comment by klinbee** [comment]
Can do, someone else commented this on my YT video, unsure if it was also you lol, but a lot of people seemed to like those in general.

**Comment by klinbee** [comment]
https://github.com/Quidvio/Custom-Floating-Islands/releases/tag/v1.0

**Comment by jamesol1** [comment]
Thanks a lot! I've noticed with this version in particular but also the main version that water ocean/river islands seem to spawn a alot. With this version it appears to be almost 70% of the islands hollowed out with water. There isn't a way of adjust this any chance is there? Thanks again love your work!

**Comment by klinbee** [comment]
I can make a version and adjust it, let me do that really quickly.

**Comment by klinbee** [comment]
https://github.com/Quidvio/Custom-Floating-Islands/releases/tag/v1.1 

In worldgen/noise_settings/overworld.json, the fluid_level_floodedness is the noise code for the aquifers.

**Comment by Mineshaft87** [comment]
Thats a fun map! I think for me the bulky islands are the perfect size, i just wish there was a way of them being less spread out and more common! Not sure if either of you know the setting for that i can try playing around with it. Reminds me of some of the old 1.12 generators

**Comment by klinbee** [comment]
Sorry for the late response, I tried working on it but I couldn't figure out much and I have been busier lately. The function that determines the island formation is worldgen/noise_settings/overworld.json, the field "Final Density". It's a function that takes 3d noise and converts it into air or blocks depending on the noise function it uses. It's a bit complicated (to the point where even I don't know what the heck I did because it was a result of me messing around before I understood most of what I was doing). I think the ultimate solution is going to be making a better function for the noise (one that makes sense too) and using that to try and replicate it, but better.

https://misode.github.io/guides/?tags=worldgen

This is a very helpful website and I used it primarily in learning how to mess with this code. I do plan on making it better, but for now there is only so much I can do with my time. If you plan on messing with it, good luck and have fun! If you would rather just wait, that is also fine. Can't promise any dates at the moment, but I hope to do it at least within a week.
